#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = 
CFLAGS = -Wall
RESINC = 
LIBDIR = 
LIB = 
LDFLAGS = 

INC_DEBUG = $(INC) -Iinclude -I../UnitTest/src
CFLAGS_DEBUG = $(CFLAGS) -std=c++11 -g
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR) -L../UnitTest/Deliv/Release
LIB_DEBUG = $(LIB)-larmadillo ../UnitTest/Deliv/Release/libUnitTest++.a
LDFLAGS_DEBUG = $(LDFLAGS)
OBJDIR_DEBUG = obj/Debug
DEP_DEBUG = 
OUT_DEBUG = bin/Debug/clbp

INC_RELEASE = $(INC) -Iinclude -I../UnitTest/src
CFLAGS_RELEASE = $(CFLAGS) -O2 -std=c++11
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)-larmadillo ../UnitTest/Deliv/Release/libUnitTest++.a
LDFLAGS_RELEASE = $(LDFLAGS) -s
OBJDIR_RELEASE = obj/Release
DEP_RELEASE = 
OUT_RELEASE = bin/Release/clbp

OBJ_DEBUG = $(OBJDIR_DEBUG)/src/CLBP.o $(OBJDIR_DEBUG)/src/LBPMapping.o $(OBJDIR_DEBUG)/src/util.o $(OBJDIR_DEBUG)/test/RunAll.o $(OBJDIR_DEBUG)/test/testCLBP.o $(OBJDIR_DEBUG)/test/testMapping.o

OBJ_RELEASE = $(OBJDIR_RELEASE)/src/CLBP.o $(OBJDIR_RELEASE)/src/LBPMapping.o $(OBJDIR_RELEASE)/src/util.o $(OBJDIR_RELEASE)/test/RunAll.o $(OBJDIR_RELEASE)/test/testCLBP.o $(OBJDIR_RELEASE)/test/testMapping.o

all: debug release

clean: clean_debug clean_release

before_debug: 
	test -d bin/Debug || mkdir -p bin/Debug
	test -d $(OBJDIR_DEBUG)/src || mkdir -p $(OBJDIR_DEBUG)/src
	test -d $(OBJDIR_DEBUG)/test || mkdir -p $(OBJDIR_DEBUG)/test

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)/src/CLBP.o: src/CLBP.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/CLBP.cpp -o $(OBJDIR_DEBUG)/src/CLBP.o

$(OBJDIR_DEBUG)/src/LBPMapping.o: src/LBPMapping.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/LBPMapping.cpp -o $(OBJDIR_DEBUG)/src/LBPMapping.o

$(OBJDIR_DEBUG)/src/util.o: src/util.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/util.cpp -o $(OBJDIR_DEBUG)/src/util.o

$(OBJDIR_DEBUG)/test/RunAll.o: test/RunAll.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c test/RunAll.cpp -o $(OBJDIR_DEBUG)/test/RunAll.o

$(OBJDIR_DEBUG)/test/testCLBP.o: test/testCLBP.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c test/testCLBP.cpp -o $(OBJDIR_DEBUG)/test/testCLBP.o

$(OBJDIR_DEBUG)/test/testMapping.o: test/testMapping.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c test/testMapping.cpp -o $(OBJDIR_DEBUG)/test/testMapping.o

clean_debug: 
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf bin/Debug
	rm -rf $(OBJDIR_DEBUG)/src
	rm -rf $(OBJDIR_DEBUG)/test

before_release: 
	test -d bin/Release || mkdir -p bin/Release
	test -d $(OBJDIR_RELEASE)/src || mkdir -p $(OBJDIR_RELEASE)/src
	test -d $(OBJDIR_RELEASE)/test || mkdir -p $(OBJDIR_RELEASE)/test

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/src/CLBP.o: src/CLBP.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/CLBP.cpp -o $(OBJDIR_RELEASE)/src/CLBP.o

$(OBJDIR_RELEASE)/src/LBPMapping.o: src/LBPMapping.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/LBPMapping.cpp -o $(OBJDIR_RELEASE)/src/LBPMapping.o

$(OBJDIR_RELEASE)/src/util.o: src/util.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/util.cpp -o $(OBJDIR_RELEASE)/src/util.o

$(OBJDIR_RELEASE)/test/RunAll.o: test/RunAll.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c test/RunAll.cpp -o $(OBJDIR_RELEASE)/test/RunAll.o

$(OBJDIR_RELEASE)/test/testCLBP.o: test/testCLBP.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c test/testCLBP.cpp -o $(OBJDIR_RELEASE)/test/testCLBP.o

$(OBJDIR_RELEASE)/test/testMapping.o: test/testMapping.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c test/testMapping.cpp -o $(OBJDIR_RELEASE)/test/testMapping.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf bin/Release
	rm -rf $(OBJDIR_RELEASE)/src
	rm -rf $(OBJDIR_RELEASE)/test

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

